build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY:
      secure: mw1Fz5a5C0lT4CXzsOCADoo/Xa9YymZI3yjVZNR8f5GwYrVAOC2YXxyEG6NaSWZY
  matrix:
    - PYTHON_VERSION: 2.7
    # Unfortuantely, cyffld2 requires OpenMP to build correctly,
    # and appyveyor only has Visual Studio 2010 Express installed.
    # Express doesn't support OpenMP builds, only VS2010 Pro does,
    # therefore, we have to do the VS2010 builds manually.
    # - PYTHON_VERSION: 3.4

matrix:
  fast_finish: true

platform:
- x86
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/menpo/condaci/v0.2.4/condaci.py' C:\\condaci.py; echo "Done"
- cmd: python C:\\condaci.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%

install:
- cmd: git submodule update --init --recursive
- cmd: C:\\Miniconda\\python C:\\condaci.py auto ./conda --binstaruser %BINSTAR_USER% --binstarkey %BINSTAR_KEY%

