package:
  name: cyffld2
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - cython 0.21*
    - libxml2 2.9.0
    - jpeg 8d
    - eigen 3.2.2
    - fftw 3.3.4

  run:
    - python
    - libxml2 2.9.0
    - jpeg 3.2.2
    - fftw 3.3.4

test:
  imports:
  - cypico

about:
  home: https://github.com/menpo/cypico/
  license: BSD
