package:
  name: cyffld2
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - cython >=0.23
    - numpy >=1.10
    - libxml2 2.*
    - jpeg
    - eigen 3.*
    - fftw 3.*
    - msinttypes r26  # [win]

  run:
    - python
    - numpy >=1.10
    - libxml2 2.*
    - jpeg
    - fftw 3.*

test:
  requires:
    - numpy
    - pillow

  imports:
    - cyffld2

about:
  home: https://github.com/menpo/cyffld2/
  license: BSD

