package:
  name: cyffld2
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - cython 0.23.*
    - libxml2 >2.7
    - jpeg 8d
    - eigen 3.2.2
    - fftw 3.3.4
    - msinttypes r26  # [win]

  run:
    - python
    - libxml2 >2.7
    - jpeg 8d
    - fftw 3.3.4

test:
  requires:
    - numpy
    - pillow

  imports:
    - cyffld2

about:
  home: https://github.com/menpo/cyffld2/
  license: BSD

